site_name: scikit-eo

site_url: https://ytarazona.github.io/scikit-eo/

repo_url: https://ytarazona.github.io/scikit-eo/

#theme:
    #palette:
        #scheme: preference
    #name: material
    #icon:
        #repo: fontawesome/brands/github
    #features:
        #- navigation.instant
        #- search.highlight
        # - navigation.expand
        # - navigation.tabs
    #custom_dir: "docs/overrides"

theme: readthedocs

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/ytarazona/scikit-eo/issues
    - API Reference:
          - fusionrs module: fusionrs.md
          - linearTrend module: linearTrend.md
          - mla module: mla.md
          - rkmeans module: rkmeans.md
          - sma module: sma.md
          - tassCap module: tassCap.md
          - writeRaster module: writeRaster.md
